version: "3.7"
services:
  site-api-dev:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile.development
    command: node app.js
    env_file:
      - .env
    environment:
      - DB_HOST=mongo
    restart: always
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    container_name: api

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongodb:/data/db

    restart: always
