version: "3.7"
services:
  site-api-dev:
    build:
      context: ./
      dockerfile: ./.docker/dev.Dockerfile
    command: pm2 start --no-daemon app.js --watch
    env_file:
      - .env
    environment:
      - MONGODB_HOST=mongo
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "8090:8090"
    container_name: api
    depends_on:
      - mongo
    networks:
      - api-net

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongodb:/data/db

    restart: always

    networks:
      - api-net

networks:
  api-net:
    driver: bridge
