let logger = require('./tools/logger')

logger.error({error:'error occured',date:new Date()})
logger.warn({error:'error occured',date:new Date()})
logger.fail({error:'error occured',date:new Date()})
logger.system({error:'error occured',date:new Date()})
logger.db({error:'error occured',date:new Date()})
logger.timeout({error:'error occured',date:new Date()})
logger.internal({error:'error occured',date:new Date()})
logger.error({error:'error occured',date:new Date()})
logger.error({error:'error occured',date:new Date()})
logger.error({error:'error occured',date:new Date()})
logger.error({error:'error occured',date:new Date()})
logger.error({error:'error occured',date:new Date()})
logger.error({error:'error occured',date:new Date()})