module.exports = {
    live:{
        httpPort:8093,
        httpURL:'https://photos.zemuldo.com',
    },
    production:{
        httpPort:8093,
        httpURL:'https://photos.zemuldo.com',
    },
    dev:{
        httpPort:8093,
        wsURL:'ws://localhost:8091',
        httpURL:'http://localhost:8091'
    },
    development:{
        httpPort:8093,
        wsURL:'ws://localhost:8091',
        httpURL:'http://localhost:8091',
        serverURL:'https://localhost:8080'
    }
}